### ISSUE TITLE
bug: 🐝  Error when setting `activeOnly` to `false`

### ISSUE THREAD

**Issue by ThomasAribart** [JamesIves/github-sponsors-readme-action#818]
### Describe the bug

Hi and thanks for this awesome action 🙌

I tried to run the action code with `ts-node`,  and I get the following error when setting the `activeOnly` setting to `false`, during the template generation:

`There was an error generating the updated file: Cannot read properties of null (reading 'privacyLevel') ❌`

Everything works fine when I leave it to `true`.

### Reproduction Steps

```
// myScript.ts
import run from "@jamesives/github-sponsors-readme-action";

void run({
  file: "README.md",
  token: <PAT_HERE>,
  template: `<a href="https://github.com/{{ login }}"><img src="https://github.com/{{ login }}.png" width="60px" alt="{{ name }}" /></a>`,
  marker: "sponsors",
  minimum: 0,
  maximum: 100000000,
  organization: false,
  activeOnly: false,
  fallback: "fallback",
});
```

`yarn ts-node myScript.ts`

### Logs

```
Checking configuration and initializing… 🚚
Fetching data from the GitHub API as User… ⚽
Generating updated README.md file… 📁
Generating template… ✨
::error::There was an error generating the updated file: Cannot read properties of null (reading 'privacyLevel') ❌
There was an error generating sponsors. ❌
::set-env name=sponsorshipStatus::failed

::set-output name=sponsorshipStatus::failed
```

### Workflow

```yml
It was outside of a workflow
```

**Comment by JamesIves** [comment]
Thanks for the report- sometimes these API's can be a little sporadic with their return. I've gone ahead and added a null check for `priavcyLevel`, you should be able to test it by pulling `1.4.4`!

**Comment by ThomasAribart** [comment]
Hi @JamesIves !

I confirm that it works with 1.5 🙌

However, the same error arises when I set `includePrivate: true` : `There was an error generating the updated file: Cannot read properties of null (reading 'tier')`.

Also, it seems that no sponsor is fetched when I set a `minimum` other than `0` 🤔

**Comment by JamesIves** [comment]
Ah I see that the function isn't properly setting the default config when used outside of GitHub Actions, I can go ahead and apply a patch version for that. Not sure _why_ you might be getting that tier error though, it could just be due to a misconfig which this patch should resolve. Gave this a quick test using my own PAT and everything seemed to work as expected after making this change. 

Give `1.5.1` a try, I just published it. You should only need to set `token` in the object now and you'll get the same defaults that are applied in the actions version, ie you'll no longer need to set all the fields manually such as minimum and maximum to simply get all sponsors. 

```js
run({
  token: process.env.GITHUB_TOKEN
})
```

**Comment by JamesIves** [comment]
@ThomasAribart Did the above work?
